name: Deploy to Production
on:
  push:
    branches: [ main ]

jobs:
  running-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout ⭕
        uses: actions/checkout@v2
      - name: Starting
        run: echo Starting pipeline
      - name: Installion dependencies and running tests 🔧
        run: |
          echo Installing dependencies
          yarn
          echo Running tests...
          yarn test