name: Running tests
on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  running-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    env:
      REACT_APP_API_KEY: ${{ env.REACT_APP_API_KEY }}
    steps:
      - name: Checkout ⭕
        uses: actions/checkout@v2
      - name: Starting
        run: echo Starting pipeline
      - name: Installion dependencies and running tests 🔧
        run: |
          echo Installing dependencies
          yarn
          echo Running tests...
          yarn test
